ALTER TABLE [dbo].[FundTypeXUsers]
    ADD CONSTRAINT [PK_FundTypeXUsers] PRIMARY KEY CLUSTERED ([FundTypeID] ASC, [UserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

