ALTER TABLE [dbo].[HoursInMonths]
    ADD CONSTRAINT [PK_HoursInMonths] PRIMARY KEY CLUSTERED ([Month] ASC, [Year] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

